- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    # - id: go-vet
    # - id: validate-toml
    # - id: no-go-testing
    # - id: gometalinter
    #   args: ['./...']
    # - id: golangci-lint
    # - id: go-critic
    - id: go-unit-tests
    # - id: go-build
    # - id: go-mod-tidy