version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    volumes:
      - ./filestore:/store

  client:
    build:
      context: .
      dockerfile: ./build/client/Dockerfile
